filetype plugin on
filetype indent on
set nocompatible
set foldopen=all
set sm
set columns=80
set background=dark
set et
set softtabstop=2
set tabstop=2
set smarttab
set shiftwidth=2
set nobk
set nu
set backspace=indent,eol,start
set history=50
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif
autocmd FileType text setlocal textwidth=80
set autoindent
